// Automatically generated by astro-icon
// 2c223833a0d9b389f4ad9b185163f85b850d89ef2ea14b92af92352b2a61a003

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:github"
		| "fa:instagram"
		| "fa:linkedin"
		| "fa:youtube"
		| "fa:twitter"
		| "lucide:badge-check"
		| "lucide:chart-no-axes-column-increasing"
		| "lucide:briefcase-business"
		| "lucide:circle-check-big"
		| "lucide:clock-4"
		| "lucide:command"
		| "lucide:house"
		| "lucide:library"
		| "lucide:mail-plus"
		| "lucide:moon-star"
		| "lucide:move-right"
		| "lucide:notebook-pen"
		| "lucide:notepad-text"
		| "lucide:pen-line"
		| "lucide:rotate-ccw"
		| "lucide:rss"
		| "lucide:settings"
		| "lucide:square-user"
		| "lucide:sun"
		| "lucide:zap"
		| "ri:quill-pen-fill"
		| "astro-icon"
		| "linked";
}