// Automatically generated by astro-icon
// df9c37e5a983d3ea77801d1ad9717d019a2dda45696591c84885a9f18b443610

declare module "virtual:astro-icon" {
  export type Icon =
    | "fa:github"
    | "fa:instagram"
    | "fa:linkedin"
    | "fa:youtube"
    | "fa:twitter"
    | "lucide:badge-check"
    | "lucide:chart-no-axes-column-increasing"
    | "lucide:briefcase-business"
    | "lucide:clock-4"
    | "lucide:command"
    | "lucide:house"
    | "lucide:library"
    | "lucide:mail-plus"
    | "lucide:moon-star"
    | "lucide:move-right"
    | "lucide:notebook-pen"
    | "lucide:notepad-text"
    | "lucide:pen-line"
    | "lucide:rss"
    | "lucide:square-user"
    | "lucide:sun"
    | "lucide:zap"
    | "ri:quill-pen-fill"
    | "astro-icon"
    | "linked";
}
