import { ContactTemplate } from '@/components';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {}

export default function PageRoute(props: Props) {
  return (
    <main
      id='main-content'
      aria-label='Contact Page'
      className='bg-white! flex flex-col gap-20'
    >
      <ContactTemplate />
    </main>
  );
}
